apiVersion: v1
kind: ConfigMap
metadata:
  name: collect-profiles-config
  namespace: openshift-operator-lifecycle-manager
  annotations:
    ran.openshift.io/ztp-deploy-wave: "1"
data:
  pprof-config.yaml: |
    disabled: True