apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anillo-cluster
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: anillo
  project: anillo-cluster-project
  source:
    path: siteconfig
    repoURL: git@github.com:kursad-yildirim/ztp-nelde.git
    targetRevision: main
  ignoreDifferences:
    - group: cluster.open-cluster-management.io
      kind: ManagedCluster
      managedFieldsManagers:
        - controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - RespectIgnoreDifferences=true
