apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/kubernetes-nmstate-operator.openshift-nmstate: ""
  name: kubernetes-nmstate-operator
  namespace: openshift-nmstate
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  channel: "stable"
  name: kubernetes-nmstate-operator
  source: cs-redhat-operator-index-v4-18
  sourceNamespace: openshift-marketplace
  installPlanApproval: Manual
status:
  state: AtLatestKnown
